// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBllmQTqdD3HJyFcyIq75rQVgxxv9Fb9Po',
    appId: '1:919562096282:web:78bb225818f9e48e275923',
    messagingSenderId: '919562096282',
    projectId: 'fiaoexpressapp-a166b',
    authDomain: 'fiaoexpressapp-a166b.firebaseapp.com',
    storageBucket: 'fiaoexpressapp-a166b.appspot.com',
    measurementId: 'G-ZZ21P94KW2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfazadjW5kMFOpvNBXEK9UxnppenGmrT0',
    appId: '1:919562096282:android:0be9a1a9e43c165a275923',
    messagingSenderId: '919562096282',
    projectId: 'fiaoexpressapp-a166b',
    storageBucket: 'fiaoexpressapp-a166b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW4QtWOPrtTFs_SuPMpDlXjWpyA7YukMQ',
    appId: '1:919562096282:ios:fa070168d168c1c1275923',
    messagingSenderId: '919562096282',
    projectId: 'fiaoexpressapp-a166b',
    storageBucket: 'fiaoexpressapp-a166b.appspot.com',
    iosBundleId: 'com.example.fiaoExpressApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW4QtWOPrtTFs_SuPMpDlXjWpyA7YukMQ',
    appId: '1:919562096282:ios:18219ca12674c9e9275923',
    messagingSenderId: '919562096282',
    projectId: 'fiaoexpressapp-a166b',
    storageBucket: 'fiaoexpressapp-a166b.appspot.com',
    iosBundleId: 'com.example.fiaoExpressApp.RunnerTests',
  );
}
